language: perl
sudo: required
services:
  - docker
# not run tag pushes
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/

before_install:
  - docker build -t xenial -f .Dockerfile .

script:
  - docker run -v `pwd`:/build xenial
    sh -c "perl Makefile.PL && make test"

install:
  - docker run -v `pwd`:/build xenial
    sh -c "cpanm --installdeps --sudo ."

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  fast_finish: true

